# Generated by Django 5.0.6 on 2024-06-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='address',
            name='unique_address',
        ),
        migrations.AlterField(
            model_name='profilecustomuser',
            name='role',
            field=models.CharField(choices=[('DRIVER', 'DRIVER'), ('PASSENGER', 'PASSENGER'), ('BOTH', 'BOTH')], max_length=10),
        ),
    ]
