# Generated by Django 4.2.13 on 2024-06-13 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('licence_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileCustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=10, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('num_permis', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(choices=[('driver', 'DRIVER'), ('passenger', 'PASSENGER'), ('both', 'BOTH')], max_length=10)),
                ('category', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('date_delivrance', models.DateField(default=django.utils.timezone.now)),
                ('date_expiration', models.DateField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-position_name'], 'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_driver',
            new_name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_passenger',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='address',
            name='position_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('number', 'street', 'city', 'region', 'country')},
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['position_name'], name='address_positio_68b741_idx'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('number', 'street', 'city', 'region', 'country'), name='unique_address'),
        ),
        migrations.AlterModelTable(
            name='address',
            table='address',
        ),
        migrations.AddField(
            model_name='profilecustomuser',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.address'),
        ),
        migrations.AddField(
            model_name='profilecustomuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='accounts.profilecustomuser'),
        ),
    ]
