# Generated by Django 5.0.6 on 2024-06-21 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_address_unique_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='author',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='owner',
        ),
        migrations.AddField(
            model_name='profilecustomuser',
            name='address',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounts.address'),
        ),
        migrations.AddField(
            model_name='profilecustomuser',
            name='car',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='accounts.carmodel'),
        ),
    ]
