# Generated by Django 5.0.6 on 2024-06-21 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_address_author_remove_carmodel_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='address',
            name='address_positio_68b741_idx',
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='address',
            table=None,
        ),
    ]
