# Generated by Django 4.2.13 on 2024-06-16 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notification_reclaim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilecustomuser',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='accounts.profilecustomuser'),
            preserve_default=False,
        ),
    ]
