# Generated by Django 5.0.6 on 2024-06-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_trip_car_alter_trip_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='end_time',
        ),
        migrations.AddField(
            model_name='trip',
            name='minutes',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
